name: harvest_example_app
dependencies:
  browser: any
  harvest:
    git: file:///Users/lt/Projects/dart/harvest
  #git://github.com/ltackmann/harvest.git
  log4dart: any
  route: any
  web_ui: any

