name: harvest
version: 1.1.4
author: Lars Tackmann <lars@solvr.io>
description: Event store for Dart with multiple backends for easly creating event sourced applications on both the browser and VM.
homepage: https://github.com/ltackmann/harvest
dependencies:
  log4dart: '>=1.3.2 <2.0.0'
  uuid: '>=0.1.1 <0.2.0'
dev_dependencies:
  unittest: any