name: dart_store
authors: Lars Tackmann <lars@solvr.io> 
homepage: https://github.com/ltackmann/dartstore
description: >
  Event store for Dart with multiple backends. Includes functionality for easily 
  creating event sourced applications in Dart on both the client and server side.
version: 1.0.0   
dependencies:
  log4dart: any
  unittest: any
  uuid: any
